export const title = 'Super Smash Bros Melee';

export const roster = [
    'Bowser',
    'Captain Falcon',
    'Donkey Kong',
    'Dr. Mario',
    'Falco',
    'Fox',
    'Ganondorf',
    'Ice Climbers',
    'Jigglypuff',
    'Kirby',
    'Link',
    'Luigi',
    'Mario',
    'Marth',
    'Mewtwo',
    'Mr. Game & Watch',
    'Ness',
    'Peach',
    'Pichu',
    'Pikachu',
    'Roy',
    'Samus',
    'Sheik',
    'Yoshi',
    'Young Link',
    'Zelda',
] as const;
